insert into details values(1,'Director',1,'Thor',0)
insert into details values(2,'Manager',2,'IronMan',1)
insert into details values(3,'Lead',3,'Hulk',1)
insert into details values(4,'Manager',2,'CaptainAmerica',1)
insert into details values(5,'QA',4,'WarMachine',2)
insert into details values(6,'DevOPS',4,'Vision',2)
insert into details values(7,'Developer',4,'Falcon',4)
insert into details values(8,'Lead',3,'AntMan',4)
insert into details values(9,'Developer',4,'BlackWidow',3)
insert into details values(10,'Intern',5,'SpiderMan',2)


insert into detail2 values(1,'Director',10)
insert into detail2 values(2,'Manager',20)
insert into detail2 values(3,'Lead',30)
insert into detail2 values(4,'Developer',40)
insert into detail2 values(5,'QA',40)
insert into detail2 values(6,'DevOps',40)
insert into detail2 values(7,'Intern',50)
